export const PostType = {
    GET_POST_START: "GET_POST_START",
    GET_POST_SUCCESS: "GET_POST_SUCCESS",
    GET_POST_ERROR: "GET_POST_ERROR",
    EDIT_POST_START: "EDIT_POST_START",
    EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
    EDIT_POST_ERROR: "EDIT_POST_ERROR",
}