export const PostType = {
    GET_POST_START: "GET_POST_START",
    GET_POST_SUCCESS: "GET_POST_SUCCESS",
    GET_POST_ERROR: "GET_POST_ERROR",
    EDIT_POST_START: "EDIT_POST_START",
    EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
    EDIT_POST_ERROR: "EDIT_POST_ERROR",
    SINGLE_POST_START: "SINGLE_POST_START",
    SINGLE_POST_SUCCESS: "SINGLE_POST_SUCCESS",
    SINGLE_POST_ERROR: "SINGLE_POST_ERROR",
    DELETE_POST_START: "DELETE_POST_START",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    DELETE_POST_ERROR: "DELETE_POST_ERROR",
    CREATE_POST_START: "CREATE_POST_START",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_ERROR: "CREATE_POST_ERROR"
}