export const CommentsType = {
    GET_COMMENTS_START: "GET_COMMENTS_START",
    GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
    GET_COMMENTS_ERROR: "GET_COMMENTS_ERROR",
    ADD_COMMENTS_START: "ADD_COMMENTS_START",
    ADD_COMMENTS_SUCCESS: "ADD_COMMENTS_SUCCESS",
    ADD_COMMENTS_ERROR: "ADD_COMMENTS_ERROR",
}
