export const CommentsType = {
    GET_COMMENTS_START: "GET_COMMENTS_START",
    GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
    GET_COMMENTS_ERROR: "GET_COMMENTS_ERROR",
    ADD_COMMENTS_START: "ADD_COMMENTS_START",
    ADD_COMMENTS_SUCCESS: "ADD_COMMENTS_SUCCESS",
    ADD_COMMENTS_ERROR: "ADD_COMMENTS_ERROR",
    DELETE_COMMENT_START: "DELETE_COMMENT_START",
    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_ERROR: "DELETE_COMMENT_ERROR",
}
