export const UserType = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    USER_LOGOUT: "USER_LOGOUT",
}